# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-20 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0002_hosts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hosts',
            new_name='Host',
        ),
    ]
